name: Actions Test-2

on:
    workflow_run:
        workflows: [Actions Test-1]
        types: [completed]
        branches:
            - main
            - develop
    workflow_dispatch:

jobs:
    info:
        name: Basic Action Information
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion }} == 'success'
        steps:
            - name: 'Echo github.event'
              uses: actions/github-script@v6
              with:
                script: |
                    console.log("github.event.ref: ${{github.event.ref}}");
                    console.log("github.event.workflow_run.head_branch: ${{github.event.workflow_run.head_branch}}");
