name: Coverage

on:
  workflow_dispatch:
    inputs:
        branch:
            description: 'Branch in which run coverage test'
            required: true

jobs:
    coverage:
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash

        steps:
          - name: Checkout Mold Lib
            uses: actions/checkout@v4
            with:
              ref: ${{ inputs.branch }}

          - name: Get Alire v1.2.2
            uses: alire-project/setup-alire@v2

          - name: Instrument the code
            run: |
              cd tests
              alr gnatcov instrument --level=stmt --dump-trigger=atexit --projects mold_lib --no-subprojects

          - name: Build unit tests
            run: |
              cd tests
              alr build --validation -- --src-subdirs=gnatcov-instr --implicit-with=gnatcov_rts_full

          - name: Run Mold Lib unit tests
            run: |
              cd tests
              alr exec ./bin/mold_lib_tests

          - name: Run gnatcov on the trace file
            run: |
              cd tests
              alr gnatcov coverage --annotate=xcov --output-dir gnatcov_out --level=stmt --projects mold_lib --no-subprojects *.srctrace

          - name: Upload coverage reports to Codecov
            uses: rocher/gnatcov-to-codecovio-action@main
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
              branch: ${{ inputs.branch }}
