name: Unit test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/src/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/src/**'
  workflow_dispatch:

jobs:
  build:
    name: Mold Lib Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Mold Lib
      uses: actions/checkout@v3

    - name: Get Alire v1.2.2
      uses: alire-project/setup-alire@v2

    - name: Build unit tests
      run: |
        cd tests
        alr build --release

    - name: Run Mold Lib unit tests
      run: |
        cd tests
        ./bin/mold_lib_tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-actions@v3
      end:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
